const chartColumns = {
    "Team_Heading": { name: "Team Averages", heading: true },
    "Age": { name: "Age" },
    "Experience": { name: "Experience" },
    "RatingPoints": { name: "Rating Points" },
    "Supercoach": { name: "Supercoach Points" },
    "DreamTeamPoints": { name: "Fantasy Points" },
    "CoachesVotes": { name: "Coaches Votes (Average)" },
    "Kicks": { name: "Kicks" },
    "ForwardHalf": { name: "Time in Forward Half" },
    "Handballs": { name: "Handballs" },
    "Disposals": { name: "Disposals" },
    "DisposalEfficiency": { name: "Disposal Efficiency" },
    "KickingEfficiency": { name: "Kicking Efficiency" },
    "Inside50s": { name: "Inside 50s" },
    "Rebound50s": { name: "Rebound 50s" },
    "Rebound50sPerOppositionInside50s": { name: "Rebound 50 rate" },
    "MetresGained": { name: "Metres Gained" },
    "Turnovers": { name: "Turnovers" },
    "ThreatRating": { name: "Threat Rating" },
    "RetentionRating": { name: "Retention Rating" },
    "ContestedPossessions": { name: "Contested Possessions" },
    "ContestedPossessionRate": { name: "Contested Possession %" },
    "Intercepts": { name: "Intercept Possessions" },
    "GroundBallGets": { name: "Ground Ball Gets" },
    "HardBallGets": { name: "Hard Ball Gets" },
    "LooseBallGets": { name: "Loose Ball Gets" },
    "PostClearanceContestedPossessions": { name: "Post-Clearance Contested Possessions" },
    "PostClearanceGroundBallGets": { name: "Post-Clearance Ground Ball Gets" },
    "GathersFromHitout": { name: "Gathers from Hitout" },
    "CrumbingPossessions": { name: "Crumbing Possessions" },
    "HandballReceives": { name: "Handball Receives" },
    "CentreClearances": { name: "Centre Clearances" },
    "TotalClearances": { name: "Total Clearances" },
    "FirstPossessions": { name: "First Possessions" },
    "FirstPossessionToClearance": { name: "First Possession To Clearance %" },
    "Marks": { name: "Marks" },
    "MarksInside50": { name: "Marks Inside 50" },
    "ContestedMarks": { name: "Contested Marks" },
    "InterceptMarks": { name: "Intercept Marks" },
    "Goals": { name: "Goals" },
    "GoalScorers": { name: "Goal Scorers" },
    "ShotsAtGoal": { name: "Shots At Goal" },
    "GoalAssists": { name: "Goal Assists" },
    "GoalAccuracy": { name: "Goal Accuracy" },
    "GoalsPerInside50": { name: "Goals / Inside 50" },
    "ScoringShotsPerInside50": { name: "Scores / Inside 50" },
    "GoalAccuracy": { name: "Goal Accuracy" },
    "xScore": { name: "xScore" },
    "xScoreRating": { name: "xScore Rating" },
    "xScorePerShot": { name: "xScore / Shot" },
    "xScoreRatingPerShot": { name: "xScore Rating / Shot" },
    "xScorePerShot_Set": { name: "xScore / Shot (Set Shots)" },
    "xScoreRatingPerShot_Set": { name: "xScore Rating / Shot (Set Shots)" },
    "xScorePerShot_General": { name: "xScore / Shot (General Play)" },
    "xScoreRatingPerShot_General": { name: "xScore Rating / Shot (General Play)" },
    "PointsFromKickIn": { name: "Points from Kick-in" },
    "PointsFromStoppage": { name: "Points from Stoppage" },
    "PointsFromTurnover": { name: "Points from Turnover" },
    "PointsFromDefensiveHalf": { name: "Points from Defensive Half" },
    "PointsFromForwardHalf": { name: "Points from Forward Half" },
    "PointsFromCentreBounce": { name: "Points from Centre Bounce" },
    "ChainToScore": { name: "Chain To Score %" },
    "D50ToF50": { name: "Defensive 50 To Inside 50 %" },
    "D50ToScore": { name: "Defensive 50 To Score %" },
    "DefHalfToF50": { name: "Defensive Half To Inside 50 %" },
    "DefHalfToScore": { name: "Defensive Half To Score %" },
    "ContestOffensiveOneOnOnes": { name: "Offensive one-on-one contests" },
    "ContestOffensiveWinPercentage": { name: "Offensive one-on-one win %" },
    "ContestDefensiveOneOnOnes": { name: "Defensive one-on-one contests" },
    "ContestDefensiveLossPercentage": { name: "Defensive one-on-one loss %" },
    "Tackles": { name: "Tackles" },
    "TacklesInside50": { name: "Tackles Inside 50" },
    "Spoils": { name: "Spoils" },
    "HitoutsWinPercentage": { name: "Hitout Win %" },
    "HitoutsToAdvantagePercentage": { name: "Hitout To Advantage %" },
    "RuckHardBallGets": { name: "Ruck Hard Ball Gets" },

    "Opposition_Heading": { name: "Opposition Averages", heading: true },
    "RatingPoints_Opposition": { name: "Rating Points (Opposition)" },
    "Disposals_Opposition": { name: "Disposals (Opposition)" },
    "DisposalEfficiency_Opposition": { name: "Disposal Efficiency (Opposition)" },
    "KickingEfficiency_Opposition": { name: "Kicking Efficiency (Opposition)" },
    "Inside50s_Opposition": { name: "Inside 50s (Opposition)" },
    "OppositionRebound50sPerInside50s": { name: "Rebound 50 rate (Opposition)" },
    "MetresGained_Opposition": { name: "Metres Gained (Opposition)" },
    "Turnovers_Opposition": { name: "Turnovers (Opposition)" },
    "ThreatRating_Opposition": { name: "Threat Rating (Opposition)" },
    "RetentionRating_Opposition": { name: "Retention Rating (Opposition)" },
    "ContestedPossessions_Opposition": { name: "Contested Possessions (Opposition)" },
    "GroundBallGets_Opposition": { name: "Ground Ball Gets (Opposition)" },
    "HardBallGets_Opposition": { name: "Hard Ball Gets (Opposition)" },
    "LooseBallGets_Opposition": { name: "Loose Ball Gets (Opposition)" },
    "PostClearanceContestedPossessions_Opposition": { name: "Post-Clearance Contested Possessions (Opposition)" },
    "PostClearanceGroundBallGets_Opposition": { name: "Post-Clearance Ground Ball Gets (Opposition)" },
    "GathersFromHitout_Opposition": { name: "Gathers from Hitout (Opposition)" },
    "CrumbingPossessions_Opposition": { name: "Crumbing Possessions (Opposition)" },
    "HandballReceives_Opposition": { name: "Handball Receives (Opposition)" },
    "CentreClearances_Oppositi  on": { name: "Centre Clearances (Opposition)" },
    "TotalClearances_Opposition": { name: "Total Clearances (Opposition)" },
    "FirstPossessions_Opposition": { name: "First Possessions (Opposition)" },
    "FirstPossessionToClearance_Opposition": { name: "First Possession To Clearance % (Opposition)" },
    "Marks_Opposition": { name: "Marks (Opposition)" },
    "MarksInside50_Opposition": { name: "Marks Inside 50 (Opposition)" },
    "ContestedMarks_Opposition": { name: "Contested Marks (Opposition)" },
    "Goals_Opposition": { name: "Goals (Opposition)" },
    "ShotsAtGoal_Opposition": { name: "Shots At Goal (Opposition)" },
    "GoalAccuracy_Opposition": { name: "Goal Accuracy (Opposition)" },
    "GoalsPerInside50_Opposition": { name: "Goals / Inside50 (Opposition)" },
    "ScoringShotsPerInside50_Opposition": { name: "Scoring Shots / Inside50 (Opposition)" },
    "GoalAccuracy_Opposition": { name: "Goal Accuracy (Opposition)" },
    "xScore_Opposition": { name: "xScore (Opposition)" },
    "xScoreRating_Opposition": { name: "xScore Rating (Opposition)" },
    "xScorePerShot_Opposition": { name: "xScore / Shot (Opposition)" },
    "xScoreRatingPerShot_Opposition": { name: "xScore Rating / Shot (Opposition)" },
    "xScorePerShot_Set_Opposition": { name: "xScore / Shot (Set Shots) (Opposition)" },
    "xScoreRatingPerShot_Set_Opposition": { name: "xScore Rating / Shot (Set Shots) (Opposition)" },
    "xScorePerShot_General_Opposition": { name: "xScore / Shot (General Play) (Opposition)" },
    "xScoreRatingPerShot_General_Opposition": { name: "xScore Rating / Shot (General Play) (Opposition)" },
    "PointsFromKickIn_Opposition": { name: "Points from Kick-in (Opposition)" },
    "PointsFromStoppage_Opposition": { name: "Points from Stoppage (Opposition)" },
    "PointsFromTurnover_Opposition": { name: "Points from Turnover (Opposition)" },
    "PointsFromDefensiveHalf_Opposition": { name: "Points from Defensive Half (Opposition)" },
    "PointsFromForwardHalf_Opposition": { name: "Points from Forward Half (Opposition)" },
    "PointsFromCentreBounce_Opposition": { name: "Points from Centre Bounce (Opposition)" },
    "ChainToScore_Opposition": { name: "Chain To Score % (Opposition)" },
    "D50ToF50_Opposition": { name: "Defensive 50 To Inside 50 % (Opposition)" },
    "D50ToScore_Opposition": { name: "Defensive 50 To Score % (Opposition)" },
    "DefHalfToF50_Opposition": { name: "Defensive Half To Inside 50 % (Opposition)" },
    "DefHalfToScore_Opposition": { name: "Defensive Half To Score % (Opposition)" },
    "HitoutsToAdvantagePercentage_Opposition": { name: "Hitout To Advantage % (Opposition)" },

    "Difference_Heading": { name: "Differences", heading: true },
    "RatingPoints_Diff": { name: "Rating Points (Difference)" },
    "Disposals_Diff": { name: "Disposals (Difference)" },
    "Inside50s_Diff": { name: "Inside 50s (Difference)" },
    "MetresGained_Diff": { name: "Metres Gained (Difference)" },
    "ThreatRating_Diff": { name: "Threat Rating (Difference)" },
    "RetentionRating_Diff": { name: "Retention Rating (Difference)" },
    "ContestedPossessions_Diff": { name: "Contested Possessions (Difference)" },
    "GroundBallGets_Diff": { name: "Ground Ball Gets (Difference)" },
    "HardBallGets_Diff": { name: "Hard Ball Gets (Difference)" },
    "LooseBallGets_Diff": { name: "Loose Ball Gets (Difference)" },
    "PostClearanceContestedPossessions_Diff": { name: "Post-Clearance Contested Possessions (Difference)" },
    "PostClearanceGroundBallGets_Diff": { name: "Post-Clearance Ground Ball Gets (Difference)" },
    "CentreClearances_Diff": { name: "Centre Clearances (Difference)" },
    "TotalClearances_Diff": { name: "Total Clearances (Difference)" },
    "FirstPossessions_Diff": { name: "First Possessions (Difference)" },
    "Marks_Diff": { name: "Marks (Difference)" },
    "ContestedMarks_Diff": { name: "Contested Marks (Difference)" },
    "Goals_Diff": { name: "Goals (Difference)" },
    "ShotsAtGoal_Diff": { name: "Shots At Goal (Difference)" },
    "xScore_Diff": { name: "xScore (Difference)" },
    "xScoreRating_Diff": { name: "xScore Rating (Difference)" },
    "xScorePerShot_Diff": { name: "xScore / Shot (Difference)" },
    "PointsFromStoppage_Diff": { name: "Points from Stoppage (Difference)" },
    "PointsFromTurnover_Diff": { name: "Points from Turnover (Difference)" },
    "PointsFromDefensiveHalf_Diff": { name: "Points from Defensive Half (Difference)" },
    "PointsFromForwardHalf_Diff": { name: "Points from Forward Half (Difference)" },
    "PointsFromCentreBounce_Diff": { name: "Points from Centre Bounce (Difference)" }
};

const defaultX = 'Goals';
const defaultY = 'RatingPoints';

let labelColumns = ['Team'];

let highlightColumn = 'Team';
let pointImageColumn = 'Image';

const viewChartButtonTemp = document.createElement('button');
viewChartButtonTemp.id = "view-chart-button";
viewChartButtonTemp.classList = "btn btn-primary btn-sm mx-1 my-2";
viewChartButtonTemp.innerText = "View scatter chart";

const csvDownloadButtonTemp = document.querySelector('#download-csv-button');
csvDownloadButtonTemp.insertAdjacentElement('beforebegin', viewChartButtonTemp);